name: React App CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      max-parallel: 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    
    - name: Install dependencies
      run: |
        npm install
    
    - name: Lint with ESLint
      run: |
        npx eslint . --max-warnings=0
    
    - name: Test with Jest
      run: |
        npm test -- --watchAll=false
